# Generated by Django 5.0.4 on 2024-04-03 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('employee_name', models.CharField(max_length=20)),
                ('employee_location_mode', models.CharField(choices=[('pune', 'PUNE'), ('mumbai', 'MUMBAI'), ('nashik', 'NASHIK'), ('nagpur', 'NAGPUR')], max_length=20)),
                ('employee_salary_mode', models.CharField(choices=[('under 5000', 'UNDER 5000'), ('under 10000', 'UNDER 10000'), ('under 15000', 'UNDER 15000'), ('under 20000', 'UNDER 20000'), ('under 30000', 'UNDER 30000')], max_length=20)),
                ('working_time', models.IntegerField()),
            ],
        ),
    ]
